title: Kembangan-Chai Chee
url: ""
favicon: /images/MPC_logo_favicon.png
colors:
  primary-color: "#0899aa"
  secondary-color: "#aa1908"
  media-colors:
    - title: media-color-one
      color: "#0899aa"
    - title: media-color-two
      color: "#e68365"
    - title: media-color-three
      color: "#60c090"
    - title: media-color-four
      color: "#f15a4a"
    - title: media-color-five
      color: "#7573b6"
resources_name: Programmes
google_analytics: UA-228607592-1
description: Immerse in the buzz and happenings of your neighbourhood.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dv0g8syxqxm22.amplifyapp.com/
prod: https://master.dv0g8syxqxm22.amplifyapp.com/
is_government: false
